// Static factory source for dynamic execute modules. Do not serialize bundled
// functions with Function.prototype.toString() here — production wrangler/esbuild
// can rewrite named functions to use a bundle-scoped __name helper that does not
// exist inside dynamically loaded worker modules.
export const kodyRemoteProxyFactorySource = [
	'function createKodyRemoteProxy(input) {',
	'  const connectors = Object.fromEntries(',
	'    input.remoteConnectors.map((connector) => [',
	'      connector.name,',
	'      {',
	'        ...connector,',
	'        capabilitiesByName: Object.fromEntries(',
	'          connector.capabilities.map((capability) => [',
	'            capability.name,',
	'            capability,',
	'          ]),',
	'        ),',
	'      },',
	'    ]),',
	'  );',
	'  const formatNames = (names) =>',
	'    names.length > 0',
	'      ? names.map((name) => JSON.stringify(name)).join(", ")',
	'      : "none";',
	'',
	'  return new Proxy(',
	'    {},',
	'    {',
	'      get(_target, connectorName) {',
	'        if (typeof connectorName === "symbol" || connectorName === "then") {',
	'          return undefined;',
	'        }',
	'        const normalizedConnectorName = String(connectorName);',
	'        const connector = connectors[normalizedConnectorName];',
	'        if (!connector) {',
	'          throw new Error(',
	'            "Unknown remote connector \\"" + normalizedConnectorName + "\\". Available remote connectors: " + formatNames(Object.keys(connectors)) + ".",',
	'          );',
	'        }',
	'        return new Proxy(',
	'          {},',
	'          {',
	'            get(_connectorTarget, capabilityName) {',
	'              if (',
	'                typeof capabilityName === "symbol" ||',
	'                capabilityName === "then"',
	'              ) {',
	'                return undefined;',
	'              }',
	'              const normalizedCapabilityName = String(capabilityName);',
	'              if (',
	'                !connector.status.connected ||',
	'                connector.status.toolCount === 0',
	'              ) {',
	'                throw new Error(connector.status.unavailableMessage);',
	'              }',
	'              const capability =',
	'                connector.capabilitiesByName[normalizedCapabilityName];',
	'              if (!capability) {',
	'                throw new Error(',
	'                  "Unknown remote capability \\"" + normalizedCapabilityName + "\\" for connector \\"" + normalizedConnectorName + "\\". Available capabilities: " + formatNames(connector.capabilities.map((entry) => entry.name)) + ".",',
	'                );',
	'              }',
	'              return async (args) =>',
	'                await input.callTool(capability.dispatchName, args);',
	'            },',
	'          },',
	'        );',
	'      },',
	'    },',
	'  );',
	'}',
].join('\n')

export function assertGeneratedExecutorSourceIsBundleSafe(source: string) {
	if (/\b__name\b/u.test(source)) {
		throw new Error(
			'Generated executor source must not reference bundle-scoped __name helpers.',
		)
	}
}
