// Static factory source for dynamic execute modules. Do not serialize bundled
// functions with Function.prototype.toString() here — production wrangler/esbuild
// can rewrite named functions to use a bundle-scoped __name helper that does not
// exist inside dynamically loaded worker modules.
export const kodyRemoteProxyFactorySource = [
	'function createKodyRemoteProxy(input) {',
	'  const entityLabel = input.entityLabel || "MCP server";',
	'  const shortEntityLabel = input.shortEntityLabel || "MCP server";',
	'  const capabilityLabel = input.capabilityLabel || "MCP tool";',
	'  const entries = Object.fromEntries(',
	'    input.entries.map((entry) => [',
	'      entry.name,',
	'      {',
	'        ...entry,',
	'        capabilitiesByName: Object.fromEntries(',
	'          entry.capabilities.map((capability) => [',
	'            capability.name,',
	'            capability,',
	'          ]),',
	'        ),',
	'      },',
	'    ]),',
	'  );',
	'  const formatNames = (names) =>',
	'    names.length > 0',
	'      ? names.map((name) => JSON.stringify(name)).join(", ")',
	'      : "none";',
	'',
	'  return new Proxy(',
	'    {},',
	'    {',
	'      get(_target, entryName) {',
	'        if (typeof entryName === "symbol" || entryName === "then") {',
	'          return undefined;',
	'        }',
	'        const normalizedEntryName = String(entryName);',
	'        const entry = entries[normalizedEntryName];',
	'        if (!entry) {',
	'          throw new Error(',
	'            "Unknown " + entityLabel + " \\"" + normalizedEntryName + "\\". Available " + entityLabel + "s: " + formatNames(Object.keys(entries)) + ".",',
	'          );',
	'        }',
	'        return new Proxy(',
	'          {},',
	'          {',
	'            get(_entryTarget, capabilityName) {',
	'              if (',
	'                typeof capabilityName === "symbol" ||',
	'                capabilityName === "then"',
	'              ) {',
	'                return undefined;',
	'              }',
	'              const normalizedCapabilityName = String(capabilityName);',
	'              if (',
	'                !entry.status.connected ||',
	'                entry.status.toolCount === 0',
	'              ) {',
	'                throw new Error(entry.status.unavailableMessage);',
	'              }',
	'              const capability =',
	'                entry.capabilitiesByName[normalizedCapabilityName];',
	'              if (!capability) {',
	'                throw new Error(',
	'                  "Unknown " + capabilityLabel + " \\"" + normalizedCapabilityName + "\\" for " + shortEntityLabel + " \\"" + normalizedEntryName + "\\". Available capabilities: " + formatNames(entry.capabilities.map((capabilityEntry) => capabilityEntry.name)) + ".",',
	'                );',
	'              }',
	'              return async (args) =>',
	'                await input.callTool(capability.dispatchName, args);',
	'            },',
	'          },',
	'        );',
	'      },',
	'    },',
	'  );',
	'}',
].join('\n')

export function assertGeneratedExecutorSourceIsBundleSafe(source: string) {
	if (/\b__name\b/u.test(source)) {
		throw new Error(
			'Generated executor source must not reference bundle-scoped __name helpers.',
		)
	}
}
