import { post, route } from 'remix/fetch-router/routes'

export const routes = route({
	home: '/',
	chat: '/chat',
	chatThread: '/chat/:threadId',
	connectSecret: '/connect/secret',
	connectSecretApi: '/connect/secret.json',
	connectSecretApiPost: post('/connect/secret.json'),
	connectOauth: '/connect/oauth',
	accountSecrets: '/account/secrets',
	accountSecretNew: '/account/secrets/new',
	accountSecretDetail: '/account/secrets/:secretId',
	accountSecretUserDetail: '/account/secrets/user/:secretName',
	accountSecretAppDetail: '/account/secrets/app/:appId/:secretName',
	accountSecretSessionDetail: '/account/secrets/session/:sessionId/:secretName',
	accountSecretPackageDetail: '/account/secrets/package/:packageId/:secretName',
	accountSecretsApprove: '/account/secrets/approve',
	accountSecretsApi: '/account/secrets.json',
	accountSecretsApiPost: post('/account/secrets.json'),
	accountSecretsReveal: post('/account/secrets/reveal'),
	chatThreads: '/chat-threads',
	chatThreadsCreate: post('/chat-threads'),
	chatThreadsUpdate: post('/chat-threads/update'),
	chatThreadsDelete: post('/chat-threads/delete'),
	health: '/health',
	login: '/login',
	signup: '/signup',
	account: '/account',
	auth: post('/auth'),
	session: '/session',
	logout: post('/logout'),
	passwordResetRequest: post('/password-reset'),
	passwordResetConfirm: post('/password-reset/confirm'),
})
