/**
 * Type declarations for the pre-bundled deferred modules (worker-bundler and
 * the OAuth provider) generated by
 * `tools/build-worker-bundler-modules.ts` into `packages/worker/.generated/`
 * and hardlinked under `src/node_modules/.kody-generated/` (gitignored).
 * The generated files re-export the public API of the installed package, so
 * its published types are authoritative.
 */

declare module '*/node_modules/.kody-generated/worker-bundler.mjs' {
	export * from '@cloudflare/worker-bundler'
}

declare module '*/node_modules/.kody-generated/worker-bundler-typescript.mjs' {
	export * from '@cloudflare/worker-bundler/typescript'
}

declare module '*/node_modules/.kody-generated/oauth-provider.mjs' {
	export * from '@cloudflare/workers-oauth-provider'
}

declare module '*/node_modules/.kody-generated/local-execute-runtime-support.mjs' {
	export {
		moduleSourceHasInlinedKodyRuntime,
		rewriteInlinedLocalExecuteBundleSource,
	} from './package-runtime/rewrite-inlined-local-runtime.ts'
	export const localExecuteHostRuntimeModuleName: 'kody:runtime'
	export function createLocalExecuteRuntimeShimSource(
		modulePath?: string,
	): string
	export function createLocalExecutePackageRuntimeModuleSource(
		packageId: string,
	): string
}

/**
 * The platform-supplied `remix` and `@remix-run/ui` packages for package
 * apps: one code-split pre-bundle of the Workers-safe `remix/<subpath>`
 * entries plus the `@remix-run/ui/<primitive>` entries, keyed relative to
 * `node_modules/` (see `packageAppRemixSubpaths` /
 * `packageAppRemixUiSubpaths`).
 */
declare module '*/node_modules/.kody-generated/package-app-remix.mjs' {
	export const remixVersion: string
	export const remixUiVersion: string
	export const files: Record<string, string>
}
