/**
 * Type declarations for the pre-bundled worker-bundler modules generated by
 * `tools/build-worker-bundler-modules.ts` into `src/generated/` (gitignored).
 * The generated files re-export the public API of the installed package, so
 * its published types are authoritative.
 */

declare module '*/generated/worker-bundler.mjs' {
	export * from '@cloudflare/worker-bundler'
}

declare module '*/generated/worker-bundler-typescript.mjs' {
	export * from '@cloudflare/worker-bundler/typescript'
}
