export { DiscordRoute, discordRouteLoader } from './discord.tsx'
export { FaqRoute } from './faq.tsx'
export { PricingRoute, pricingRouteLoader } from './pricing.tsx'
export { PrivacyRoute } from './privacy.tsx'
export { TermsRoute } from './terms.tsx'
