import { markSecretInputFields } from '@kody-internal/shared/secret-input-schema.ts'
import { z } from 'zod'
import { defineDomainCapability } from '#mcp/capabilities/define-domain-capability.ts'
import { capabilityDomainNames } from '#mcp/capabilities/domain-metadata.ts'
import { requireMcpUser } from '#mcp/capabilities/meta/require-user.ts'
import { getSavedPackageByKodyId } from '#worker/package-registry/repo.ts'
import {
	buildAuthenticatedArtifactsRemote,
	parseArtifactTokenSecret,
} from '#worker/repo/artifacts.ts'
import {
	assertPublishedPackageSourceRepoHead,
	assertRestorablePackageSourceSnapshot,
} from '#worker/repo/source-safety-policy.ts'
import { createStubSavedPackage } from './create-stub-package.ts'
import { resolveOwnedPackageSource } from './resolve-package-source.ts'

const getGitRemoteInputSchema = z.object({
	package_id: z.string().min(1).optional(),
	kody_id: z.string().min(1).optional(),
	create: z
		.boolean()
		.optional()
		.default(false)
		.describe(
			'Set true with `kody_id` to register a new stub saved package (private, minimal scaffold) when none exists yet, then mint its remote in the same call. Existing packages are reused as-is.',
		),
	description: z
		.string()
		.min(1)
		.optional()
		.describe(
			'Package description used when `create: true` registers a new stub package. Ignored for existing packages.',
		),
	scope: z.enum(['read', 'write']).default('write'),
	ttl_seconds: z.number().int().min(60).max(86_400).default(3600),
})

const outputSchema = markSecretInputFields(
	z.toJSONSchema(
		z.object({
			package_id: z.string(),
			kody_id: z.string(),
			created: z
				.boolean()
				.describe(
					'True when this call registered a new stub saved package before minting the remote.',
				),
			remote: z.string(),
			authenticated_remote: z.string(),
			git_extra_header: z.string(),
			scope: z.enum(['read', 'write']),
			expires_at: z.string(),
			setup_commands: z.array(z.string()),
		}),
	) as Record<string, unknown>,
	['authenticated_remote', 'git_extra_header', 'setup_commands'],
) as Record<string, unknown>

function shellQuote(value: string) {
	return `'${value.replaceAll(`'`, `'"'"'`)}'`
}

export const getGitRemoteCapability = defineDomainCapability(
	capabilityDomainNames.packages,
	{
		name: 'package_get_git_remote',
		description:
			'Start or continue the git lane for saved packages: mint a short-lived Cloudflare Artifacts git remote so coding agents with local filesystem/git access can clone into a temporary directory, edit normally (including binary assets), push, and publish with package_publish_external_push. Pass `create: true` with a new `kody_id` to register a stub saved package and mint its remote in one call, so new packages can be authored via clone-edit-push instead of package_save file blobs. Write access verifies the current package source has a restorable backup snapshot before clone/edit/publish.',
		keywords: [
			'package',
			'create',
			'new',
			'scaffold',
			'git',
			'remote',
			'artifacts',
			'clone',
			'push',
			'local clone',
			'temporary directory',
		],
		readOnly: false,
		idempotent: false,
		destructive: false,
		inputSchema: getGitRemoteInputSchema,
		outputSchema,
		async handler(args, ctx) {
			const user = requireMcpUser(ctx.callerContext)
			const requestedKodyId = args.kody_id?.trim() || undefined
			let created = false
			if (args.create) {
				if (requestedKodyId === undefined || args.package_id !== undefined) {
					throw new Error(
						'`create: true` requires `kody_id` (without `package_id`); new package ids are generated by Kody.',
					)
				}
				const existing = await getSavedPackageByKodyId(ctx.env.APP_DB, {
					userId: user.userId,
					kodyId: requestedKodyId,
				})
				if (!existing) {
					await createStubSavedPackage({
						env: ctx.env,
						baseUrl: ctx.callerContext.baseUrl,
						user,
						kodyId: requestedKodyId,
						description: args.description,
					})
					created = true
				}
			}
			const { source, packageId, kodyId } = await resolveOwnedPackageSource({
				db: ctx.env.APP_DB,
				userId: user.userId,
				args: {
					package_id: args.package_id,
					kody_id: requestedKodyId,
				},
			})
			if (args.scope === 'write') {
				await assertRestorablePackageSourceSnapshot({
					env: ctx.env,
					userId: user.userId,
					source,
					operation: 'package_get_git_remote write access',
				})
			}
			const sourceHead = await assertPublishedPackageSourceRepoHead({
				env: ctx.env,
				source,
				operation: 'package_get_git_remote',
			})
			if (!sourceHead) {
				throw new Error('package_get_git_remote requires a package source.')
			}
			const { repo } = sourceHead
			const token = await repo.createToken(args.scope, args.ttl_seconds)
			const gitExtraHeader = `Authorization: Bearer ${parseArtifactTokenSecret(token.plaintext)}`
			const cloneDirectory = source.entity_id
			return {
				package_id: packageId,
				kody_id: kodyId,
				created,
				remote: sourceHead.remote,
				authenticated_remote: buildAuthenticatedArtifactsRemote({
					remote: sourceHead.remote,
					token: token.plaintext,
				}),
				git_extra_header: gitExtraHeader,
				scope: args.scope,
				expires_at: token.expiresAt,
				setup_commands: [
					`git -c http.extraHeader=${shellQuote(gitExtraHeader)} clone ${shellQuote(sourceHead.remote)} ${shellQuote(cloneDirectory)}`,
					`cd ${shellQuote(cloneDirectory)}`,
					`git remote add kody ${shellQuote(sourceHead.remote)}`,
					`git config remote.kody.fetch '+refs/heads/*:refs/remotes/kody/*'`,
					`git config --add remote.kody.fetch '+refs/notes/*:refs/notes/*'`,
					`git -c http.extraHeader=${shellQuote(gitExtraHeader)} fetch kody 'refs/notes/*:refs/notes/*'`,
					`git -c http.extraHeader=${shellQuote(gitExtraHeader)} push kody HEAD:${shellQuote(sourceHead.defaultBranch)}`,
				],
			}
		},
	},
)
