import { createHash } from 'node:crypto'
import { mkdir, open, readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { sortGuidesByAuthoredOrder } from '#worker/guides/guide-order.ts'
import {
	parseGuideMarkdown,
	type Guide,
	type GuideMetadata,
} from '#worker/guides/parse-frontmatter.ts'
import {
	rewriteRelativeGuideLinks,
	type GuideSourceDir,
} from '#worker/guides/rewrite-relative-links.ts'
import { isExecutedDirectly } from './node-runtime.ts'

/**
 * Generates the guide metadata/full-catalog modules that
 * `#worker/guide-catalog-modules.ts` exposes to the `coding_guide_get`
 * capability, from the canonical markdown in `docs/guides/`.
 *
 * Why: `#worker/guides/catalog.ts` statically imports every guide's raw
 * markdown and parses its frontmatter at module scope so the web `/guides`
 * pages always have the full catalog ready. Merely *registering* the MCP
 * `coding_guide_get` capability must not pay that same cost on every
 * platform/runtime Worker isolate cold start — the capability module only
 * needs a handful of small fields (id, summary, provider, …) to build its
 * description/keywords/input schema, and needs full guide bodies only while
 * actually handling a request.
 *
 * This generator produces two gitignored modules under
 * `packages/worker/src/generated/`:
 *
 * - `guide-metadata.mjs` — every guide's frontmatter (no body). Small enough
 *   to statically import; costs no per-guide parsing at runtime.
 * - `guide-catalog.mjs` — the full parsed catalog (with bodies, links
 *   rewritten the same way `#worker/guides/catalog.ts` does). Matches the
 *   `generated/*.mjs` `find_additional_modules` rule in `wrangler.jsonc`, so
 *   Wrangler uploads it as a separate external module, excluded from the
 *   main worker script, that only loads when the *dynamic* `import()` in
 *   `#worker/guide-catalog-modules.ts` actually runs — unlike an ordinary
 *   dynamic import of an in-repo module, which Wrangler still bundles into
 *   the main script, adding to the code V8 must parse and link on every
 *   cold start even though execution of that code stays deferred.
 *
 * Both modules reuse `parseGuideMarkdown`/`rewriteRelativeGuideLinks` (the
 * same functions `catalog.ts` uses) so parsing/link-rewriting behavior never
 * drifts between the web catalog and the generated modules.
 *
 * Deterministic for a given `docs/guides/` tree, so a stamp file makes
 * re-runs a no-op (this runs in front of every wrangler dev/build/deploy and
 * once per vitest run).
 */

const repoRoot = fileURLToPath(new URL('..', import.meta.url))
const guidesSourceDir = path.join(repoRoot, 'docs/guides')
const generatedDir = path.join(repoRoot, 'packages/worker/src/generated')
const stampPath = path.join(generatedDir, 'guide-catalog.stamp.json')
const metadataOutputPath = path.join(generatedDir, 'guide-metadata.mjs')
const catalogOutputPath = path.join(generatedDir, 'guide-catalog.mjs')

const generatedFileHeader =
	'// AUTO-GENERATED by tools/build-guide-catalog-modules.ts from docs/guides/**/*.md. Do not edit.\n'

/** Guide source files are markdown, excluding docs (no frontmatter fence). */
function isGuideMarkdownFile(fileName: string) {
	return fileName.endsWith('.md') && fileName.toLowerCase() !== 'readme.md'
}

async function findGuideMarkdownFiles(): Promise<ReadonlyArray<string>> {
	const entries = await readdir(guidesSourceDir, {
		recursive: true,
		withFileTypes: true,
	})
	return entries
		.filter((entry) => entry.isFile() && isGuideMarkdownFile(entry.name))
		.map((entry) => path.join(entry.parentPath, entry.name))
		.toSorted((a, b) => a.localeCompare(b))
}

function slugFromFilePath(filePath: string): string {
	return path.basename(filePath, '.md')
}

async function readGuideSources(
	filePaths: ReadonlyArray<string>,
): Promise<ReadonlyArray<{ slug: string; raw: string }>> {
	return Promise.all(
		filePaths.map(async (filePath) => ({
			slug: slugFromFilePath(filePath),
			raw: await readFile(filePath, 'utf8'),
		})),
	)
}

/**
 * Parses every guide, rewrites relative links, and sorts into authored
 * order, mirroring `buildCatalog()` in `#worker/guides/catalog.ts` exactly
 * (both use `sortGuidesByAuthoredOrder` from the shared `guide-order.ts`),
 * so `coding_guide_get`'s schema description never drifts from the web
 * catalog's order.
 */
function buildFullCatalog(
	sources: ReadonlyArray<{ slug: string; raw: string }>,
): ReadonlyArray<Guide> {
	const parsed = sources.map(({ slug, raw }) => parseGuideMarkdown(slug, raw))

	const ids = new Set<string>()
	for (const guide of parsed) {
		if (ids.has(guide.id)) {
			throw new Error(`Duplicate guide id "${guide.id}".`)
		}
		ids.add(guide.id)
	}

	const knownSlugs = new Set(parsed.map((guide) => guide.slug))
	const rewritten = parsed.map((guide) => {
		const sourceDir: GuideSourceDir =
			guide.category === 'provider' ? 'docs/guides/providers' : 'docs/guides'
		return {
			...guide,
			body: rewriteRelativeGuideLinks({
				body: guide.body,
				sourceDir,
				knownSlugs,
			}),
		}
	})
	return sortGuidesByAuthoredOrder(rewritten)
}

function toMetadata(
	guides: ReadonlyArray<Guide>,
): ReadonlyArray<GuideMetadata> {
	return guides.map(({ body, ...metadata }) => metadata)
}

/**
 * Renders `export const <exportName> = JSON.parse(<json-string-literal>)`.
 * Round-tripping through a JS string literal (rather than splicing the JSON
 * text in as an object literal) sidesteps any edge cases in embedding
 * arbitrary guide markdown as JS source syntax.
 */
function renderGeneratedModule(exportName: string, data: unknown): string {
	const json = JSON.stringify(data)
	const jsonAsStringLiteral = JSON.stringify(json)
	return `${generatedFileHeader}export const ${exportName} = JSON.parse(${jsonAsStringLiteral})\n`
}

async function buildStampContent(filePaths: ReadonlyArray<string>) {
	const generatorSource = await readFile(fileURLToPath(import.meta.url), 'utf8')
	const parseFrontmatterSource = await readFile(
		path.join(repoRoot, 'packages/worker/src/guides/parse-frontmatter.ts'),
		'utf8',
	)
	const rewriteLinksSource = await readFile(
		path.join(repoRoot, 'packages/worker/src/guides/rewrite-relative-links.ts'),
		'utf8',
	)
	const guideFileContents = await Promise.all(
		filePaths.map(async (filePath) => ({
			filePath: path.relative(repoRoot, filePath),
			raw: await readFile(filePath, 'utf8'),
		})),
	)
	const hash = createHash('sha256')
		.update(generatorSource)
		.update(parseFrontmatterSource)
		.update(rewriteLinksSource)
		.update(JSON.stringify(guideFileContents))
		.digest('hex')
	return JSON.stringify({ hash }, null, '\t')
}

async function readStamp(): Promise<string | null> {
	try {
		return await readFile(stampPath, 'utf8')
	} catch {
		return null
	}
}

async function fsyncGeneratedDir() {
	const handle = await open(generatedDir, 'r')
	try {
		await handle.sync()
	} finally {
		await handle.close()
	}
}

/** Idempotent: skips regeneration when the stamp already matches. */
export async function ensureGuideCatalogModules() {
	const filePaths = await findGuideMarkdownFiles()
	const stampContent = await buildStampContent(filePaths)
	if ((await readStamp()) === stampContent) return

	const sources = await readGuideSources(filePaths)
	const fullCatalog = buildFullCatalog(sources)
	const metadata = toMetadata(fullCatalog)

	await mkdir(generatedDir, { recursive: true })
	await writeFile(
		metadataOutputPath,
		renderGeneratedModule('guideMetadata', metadata),
	)
	await writeFile(
		catalogOutputPath,
		renderGeneratedModule('guides', fullCatalog),
	)
	await writeFile(stampPath, stampContent)
	// Flush before `wrangler dev` starts watching `src/` (see the matching
	// note in tools/build-worker-bundler-modules.ts / Friction #1789).
	await fsyncGeneratedDir()
}

if (isExecutedDirectly(import.meta.url)) {
	await ensureGuideCatalogModules()
}
