import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, relative, resolve } from 'node:path'
import { build } from 'esbuild'

const projectRoot = resolve(import.meta.dirname, '..')
const generatedOutputPath = resolve(
	projectRoot,
	'packages/worker/src/mcp/generated/codemode-sandbox-modules.ts',
)

const moduleEntries = {
	'@kody/codemode-utils': resolve(
		projectRoot,
		'packages/worker/src/mcp/execute-modules/codemode-utils.ts',
	),
} as const satisfies Record<string, string>

async function main() {
	const modules = await Promise.all(
		Object.entries(moduleEntries).map(async ([specifier, entryPoint]) => {
			const result = await build({
				entryPoints: [entryPoint],
				bundle: true,
				format: 'esm',
				platform: 'browser',
				target: 'es2022',
				write: false,
				logLevel: 'silent',
			})
			const output = result.outputFiles[0]
			if (!output) {
				throw new Error(`No bundled output generated for ${specifier}.`)
			}
			return [specifier, output.text] as const
		}),
	)

	const generatedSource = `// Generated by ${relative(
		projectRoot,
		resolve(import.meta.dirname, 'build-codemode-sandbox-modules.ts'),
	)}. Do not edit by hand.

export const codemodeSandboxModules = ${JSON.stringify(
		Object.fromEntries(
			modules.map(([specifier, content]) => [
				specifier,
				{
					js: content,
				},
			]),
		),
		null,
		2,
	)} as Record<string, { js: string }>
`

	await mkdir(dirname(generatedOutputPath), { recursive: true })
	await writeFile(generatedOutputPath, generatedSource, 'utf8')
}

await main()
