import { repoDomain } from './domain.ts'

export { repoDomain } from './domain.ts'
export { repoCreateCapability } from './repo-create.ts'
export { repoListCapability } from './repo-list.ts'
export { repoGetCapability } from './repo-get.ts'
export { repoDeleteCapability } from './repo-delete.ts'
export { repoGetGitRemoteCapability } from './repo-get-git-remote.ts'
export { repoPromoteToPackageCapability } from './repo-promote-to-package.ts'
export { repoApplyPatchCapability } from './repo-apply-patch.ts'
export { repoCommitCapability } from './repo-commit.ts'
export { repoDiffCapability } from './repo-diff.ts'
export { repoDiscardSessionCapability } from './repo-discard-session.ts'
export { repoEditFilesCapability } from './repo-edit-files.ts'
export { repoGetCheckStatusCapability } from './repo-get-check-status.ts'
export { repoGetSessionCapability } from './repo-get-session.ts'
export { repoListSessionsCapability } from './repo-list-sessions.ts'
export { repoLogCapability } from './repo-log.ts'
export { repoOpenSessionCapability } from './repo-open-session.ts'
export { repoPublishSessionCapability } from './repo-publish-session.ts'
export { repoReadFileCapability } from './repo-read-file.ts'
export { repoRebaseSessionCapability } from './repo-rebase-session.ts'
export { repoRestoreCapability } from './repo-restore.ts'
export { repoRunChecksCapability } from './repo-run-checks.ts'
export { repoShowPublishNoteCapability } from './repo-show-publish-note.ts'
export { repoSearchCapability } from './repo-search.ts'
export { repoStatusCapability } from './repo-status.ts'
export { repoTreeCapability } from './repo-tree.ts'
export { repoWriteFileCapability } from './repo-write-file.ts'

export const repoCapabilities = repoDomain.capabilities
